version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions-packages:
        patterns:
          - "@actions/*"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "typescript"
        versions: [">=7"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
