name: 'Source to Image Build'
description: 'This action allows you to build an image of the application using source code'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  builder_image:
    description: 'The location of the s2i builder image.'
    required: true
  image_name:
    description: 'The Name of the image to build'
    required: true
  image_tag:
    description: 'The version of the image to build'
    default: 'latest'
    required: false
  path_context:
    description: 'The location of the path to run s2i from'
    default: '.'
    required: false
  log_level:
    description: 'Log level when running the S2I'
    default: '1'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'