name: 'Source to Image Build'
description: 'Build a container image from source code'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  builder_image:
    description: 'The path of the s2i builder image.'
    required: true
  image:
    description: 'The Name of the image to build'
    required: true
  tags:
    description: 'The tags of the image to build. For multiple tags, seperate by a space. For example, "latest v1".'
    default: 'latest'
    required: false
  path_context:
    description: 'The location of the path to run s2i from'
    default: '.'
    required: false
  log_level:
    description: 'Log level when running the S2I'
    default: '1'
    required: false
  env_vars:
    description: 'List of environment variable key-value pairs to pass to the s2i builder context'
    required: false
  include_git:
    description: 'Include all files in tar during build which includes .git directory'
    required: false
    default: 'false'
outputs:
  image:
    description: 'Name of the image built'
  tags:
    description: 'List of the tags that were created, separated by spaces'
runs:
  using: 'node20'
  main: 'dist/index.js'
