# This example workflow will build container image
# of the application using source to image build
# startegy and push the image to quay.io (Image registry)

name: Build and Push
on: [push, pull_request]

jobs:
  test-s2i-job:
    runs-on: ubuntu-latest
    name: A job to build and push image
    steps:
      
      # Checkout spring petclinic repository
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          repository: spring-projects/spring-petclinic

      # Setup S2i and Build container image
      - name: Setup and Build
        uses: redhat-actions/s2i-build@main
        with:
          path_context: '.'
          builder_image: 'registry.access.redhat.com/openjdk/openjdk-11-rhel7'
          image_name: spring-petclinic-s2i
          image_tag: 'v1'
          
      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@main
        with:
          image: 'spring-petclinic-s2i'
          tag: 'v1'
          registry: ${{ secrets.REPO }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
